api_platform:
    title: 'Nation Sounds'
    description: "Api utilisée pour l'application mobile Nation Sounds"
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/json+ld']
        html:
            mime_types: ['text/html']
