easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    site_name : 'MSPR <em style="font-size:80%">Back-end</em>'
    design:
        assets:
              favicon: 'https://www.vippng.com/png/detail/44-447021_icon-guitar.png'
        brand_color : red
        menu:
            - label: 'Environnement'
              icon: 'fas fa-map-marked-alt'
              children:
                  - {entity: Map , icon: 'map-marker-alt', label: 'Carte'}
                  - {entity: Buvette , icon: 'glass-cheers' , label: 'Buvettes'}
                  - {entity: Parking , icon: 'parking' , label: 'Parkings'}
                  - {entity: Boutique , icon: 'shopping-basket' , label: 'Boutiques'}
                  - {entity: Concert , icon: 'music' , label: 'Concerts'}
                  - {entity: Evenement , icon: 'calendar-alt' , label: 'Evenements'}
                  - {entity: StandInformation , icon: 'info-circle' , label: "Stands d'informations"}
                  - {entity: Wc , icon: 'restroom' , label: 'Toilettes'}
                  - {entity: ObjetPerdu , icon: 'umbrella' , label: 'Objets perdus'}

            - label: 'Informations'
              icon: 'info'
              children:
                  - {entity: InformationGenerale , icon: 'question-circle' , label: 'Informations générale'}
                  - {entity: InformationUrgente , icon: 'exclamation-triangle' , label: 'Informations Urgente'}
              
            - label: 'Elements'
              icon: 'hand-middle-finger'
              children:
                  - {entity: Billeterie , icon: 'credit-card' , label: 'Billeterie'}
                  - {entity: Faq , icon: 'question' , label: 'FAQ'}
                  - {entity: Partenaire , icon: 'handshake'  , label: 'Partenaires'}
                  - {entity: ReseauxSociaux , icon: 'share-alt'  , label: 'Reseaux sociaux'}

    entities:
      # ------------ Environnement--------------
        Map:
            class: App\Entity\Map      
            label: 'une carte'
            list:
                fields:
                    - parking           
                    - boutique           
                    - Wc           
                    - Evenement           
                    - Concert           
                    - { property: objetPerdu , label: "Objets perdus" }          
                    - { property: standInformation , label: "Stands d'informations" }           
                    - buvette
                actions:
                    - {name: edit , icon: 'pencil', label: false, css_class: 'btn btn-secondary' }
                    - {name: delete , icon: 'trash-alt', label: false, css_class: 'btn btn-danger' }
                title: "Elements de la carte"


        Buvette:
            class: App\Entity\Buvette
        Parking:
            class: App\Entity\Parking
        Billetterie:
            class: App\Entity\Billetterie
        Boutique:
            class: App\Entity\Boutique
        Concert:
            class: App\Entity\Concert
            list:
              fields:
                    - dateDebut
                    - dateFin
              sort: ['dateDebut', 'ASC']
              
        Evenement:
            class: App\Entity\Evenement
        StandInformation:
            class: App\Entity\StandInformation
        Wc:
            class: App\Entity\Wc
        ObjetPerdu:
            class: App\Entity\ObjetPerdu
        
            # ------------Fin Environnement--------------

            # ------------ Element --------------
        Billeterie:
            class: App\Entity\Billetterie
        Faq:
            class: App\Entity\Faq
        InformationGenerale:
            class: App\Entity\InformationGenerale
        InformationUrgente:
            class: App\Entity\InformationUrgente
        Partenaire:
            class: App\Entity\Partenaire
        ReseauxSociaux:
            class: App\Entity\ReseauxSociaux
            # ------------ Fin Element --------------
