easy_admin:
    design:
        assets:
              css: ['/bundles/easyadmin/custom_backend.css']
              favicon: 'https://www.vippng.com/png/detail/44-447021_icon-guitar.png'
        brand_color : red
        menu:
            - label: 'Utilisateurs'
            - label: 'Utilisateur'
              icon: 'users-cog'
              children:
                  - {entity: UserSite , icon: 'far fa-user' , label: 'Utilisateurs admin' , permission: 'ROLE_SUPER_ADMIN'}
                  - {entity: UserAppli , icon: 'fas fa-users' , label: 'Utilisateurs Application'}

            - label: 'Informations festival'
            - {entity: Chanteur , icon: 'fas fa-microphone' , label: 'Chanteurs'}
            - {entity: Scene , icon: 'fas fa-map-signs' , label: 'Scenes'}
            
            - label: 'Informations générales'
            - label: 'Environnement'
              icon: 'fas fa-map-marked-alt'
              children:
                  - {entity: Buvette , icon: 'glass-cheers' , label: 'Buvettes'}
                  - {entity: Parking , icon: 'parking' , label: 'Parkings'}
                  - {entity: Boutique , icon: 'shopping-basket' , label: 'Boutiques'}
                  - {entity: Concert , icon: 'music' , label: 'Concerts'}
                  - {entity: Evenement , icon: 'calendar-alt' , label: 'Evenements'}
                  - {entity: StandInformation , icon: 'info-circle' , label: "Stands d'informations"}
                  - {entity: Wc , icon: 'restroom' , label: 'Toilettes'}
                  - {entity: ObjetPerdu , icon: 'umbrella' , label: 'Objets perdus'}

            - label: 'Informations'
              icon: 'info'
              children:
                  - {entity: InformationGenerale , icon: 'question-circle' , label: 'Informations générale'}
                  - {entity: InformationUrgente , icon: 'exclamation-triangle' , label: 'Informations urgente'}
              
            - {entity: Billeterie , icon: 'credit-card' , label: 'Billeterie'}
            - {entity: ReseauxSociaux , icon: 'share-alt'  , label: 'Reseaux sociaux'}
            - {entity: Partenaire , icon: 'handshake'  , label: 'Partenaires'}
            - {entity: Faq , icon: 'question' , label: 'FAQ'}
            - {entity: Apropos , icon: 'comment-alt' , label: 'À propos'}

            - label: 'Données externes'
            - {label: 'API' ,icon: 'database' , url: '/admin/api' , target: '_blank' }
            - {label: 'Coordonnées GPS' ,icon: 'map-marker-alt' , url: 'https://www.coordonnees-gps.fr/' , target: '_blank' }
